apiVersion: v1
kind: Service
metadata:
  name: pgvector
  namespace: db-pgvector
spec:
  type: ClusterIP
  selector:
    app: pgvector
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
---
# Headless Service fürs StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: pgvector-headless
  namespace: db-pgvector
spec:
  clusterIP: None
  selector:
    app: pgvector
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
